### ISSUE TITLE
[Bare Minimum] Todo CRUD 기능 구현

### ISSUE THREAD

**Issue by jwp9633** [jwp9633/pre-project-react-tutorial#2]
### 만들고자 하는 기능이 무엇인가요?
Todo CRUD 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 더미 데이터 생성
2. [ ] Todo 컴포넌트 제작
3. [ ] Read 기능 구현
4. [ ] Delete 기능 구현
5. [ ] Update 기능 구현
6. [ ] Create 기능 구현

### 예상 작업 시간
3h
